Practise Quest: make map backed repository and filter method
At-first-music/qa-automation-java pull request #14
Opened 2021-09-11 08:45 UTC by At-first-music

make map backed repository and filter method and tests

2021-09-16 06:14 UTC, andr92 requested changes

2021-09-16 06:14 UTC, andr92 commented on src/test/java/com/tinkoff/edu/AppTest.java
> +
думаю, что не обязательно прям 3 PERSON создавать, можно наверно и одним обойтись

2021-09-16 06:14 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/models/CreditResponse.java
> +
лишняя строка

2021-09-16 19:26 UTC, At-first-music commented on src/test/java/com/tinkoff/edu/AppTest.java
> +
Поправил

2021-09-16 19:26 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/models/CreditResponse.java
> +
удалил

2021-09-17 08:26 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/MapBackendCreditCalcRepository.java
> +    public List<CreditResponse> getCreditResponsesByClientType(ClientType clientType) {
все таки кажется лучше перенести это в сервис

2021-09-17 19:52 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/repository/MapBackendCreditCalcRepository.java
> +    public List<CreditResponse> getCreditResponsesByClientType(ClientType clientType) {
перенес

2021-09-19 14:48 UTC, merged