Practise quest: add fileBackendRepository
At-first-music/qa-automation-java pull request #15
Opened 2021-09-27 07:59 UTC by At-first-music

Добавление FileBackendRepository

2021-09-27 09:42 UTC, andr92 requested changes

2021-09-27 09:42 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/FileBackendCreditCalcRepository.java
> +            Files.write(fileWithCreditResponses.toPath(),
Files.writeString

2021-09-27 09:42 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/FileBackendCreditCalcRepository.java
> +}
подравняй код в классе пожалуйста. alt ctrl L

2021-09-28 14:43 UTC, andr92 requested changes

2021-09-28 14:43 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/CreditCalcRepository.java
> +    File fileWithCreditResponses = new File("FileWithCreditResponses.txt");
не уверен, что для не файловых репозиториев это будет нужно. Так что можно оставить и в репо с файлами просто

2021-09-28 14:43 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/service/CreditCalcService.java
> +    List<String> getCreditResponsesByClientType(ClientType clientType) throws IOException;
а почему тут это список стрингов, а ниже метод с похожим названием возвращает CreditResponse?

2021-09-28 15:57 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/service/CreditCalcService.java
> +    List<String> getCreditResponsesByClientType(ClientType clientType) throws IOException;
нижним методом получаю одну заявку, а этим методом - множество, то есть желательно также получать множество CreditResponse?

2021-09-28 15:57 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/repository/CreditCalcRepository.java
> +    File fileWithCreditResponses = new File("FileWithCreditResponses.txt");
поправил

2021-09-28 15:57 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/repository/FileBackendCreditCalcRepository.java
> +            Files.write(fileWithCreditResponses.toPath(),
поправил

2021-09-28 19:06 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/service/CreditCalcService.java
> +    List<String> getCreditResponsesByClientType(ClientType clientType) throws IOException;
мне кажется логичнее будет продолжать работать с объектами CreditResponse

2021-09-29 07:33 UTC, At-first-music commented on src/main/java/com/tinkoff/edu/app/service/CreditCalcService.java
> +    List<String> getCreditResponsesByClientType(ClientType clientType) throws IOException;
поправил

2021-09-30 06:34 UTC, merged